apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0sec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0sec
    app.kubernetes.io/part-of: tkrw-pr712-0075-0061-app
  name: devfile-sample-0sec
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0sec
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0sec
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-0sec@sha256:871bccaf983cf8c7578a966694c251e49624a1d5fd754f984533e118349d1bbf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
